/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.epissoft.sanguchito.vista.reportes;

import com.epissoft.sanguchito.vista.Sanguchito;
import com.epissoft.sanguchito.modelo.reportes.*;
import java.util.Calendar;
import com.epissoft.sanguchito.vista.*;
import com.epissoft.sanguchito.vista.utilitarios.ActualizarReloj;
import com.epissoft.sanguchito.vista.utilitarios.CargarFecha;
import com.epissoft.sanguchito.vista.utilitarios.BotonesComunes;
/**
 *
 * @author Roger
 */
public class GeneracionReportes2 extends javax.swing.JInternalFrame {

    /**
     * Creates new form GeneracionReportes2
     */
    ReportexCategoria mostrar = new ReportexCategoria();
    ReporteXProducto mostrarp = new ReporteXProducto();
    ReporteVentas mostrarg = new ReporteVentas();
    ReporteGastos mostrarga = new ReporteGastos();
    RerportePersonal mostrarper = new RerportePersonal();
    ReporteAlmacen mostraral = new ReporteAlmacen();
    
    Calendar calendario = Calendar.getInstance();
    String _dia=Integer.toString(calendario.get(Calendar.DATE));
    String _mes=Integer.toString(calendario.get(Calendar.MONTH));
    String _anio=Integer.toString(calendario.get(Calendar.YEAR));
    
   

    public static String categoria;
    public static String producto;
    public static int opcion;
    public static String TipoReporte;
    public static String modulo;
    public static String nombre;
    
   
    
    public GeneracionReportes2() {
        initComponents();
        TextUsuario.setText(ManejoSesion.getUsuario());
        ActualizarReloj actualizar=new ActualizarReloj(jTextField2);
        CargarFecha.cargarFechaActual(jTextField3);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TextUsuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CalendarFechaInicio = new com.toedter.calendar.JDateChooser();
        CalendarFechaFin = new com.toedter.calendar.JDateChooser();
        BotonVentas = new javax.swing.JButton();
        BotonGastos = new javax.swing.JButton();
        BotonAlmacen = new javax.swing.JButton();
        BotonAsistencia = new javax.swing.JButton();
        BotonBarraVertical = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        BotonBarraHorizontal = new javax.swing.JButton();
        BotonTorta = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 744));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 186));

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 18));
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setText("Bienvenido  a  SanGuchitoSoft");

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18));
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText(" Usuario :");

        TextUsuario.setEditable(false);
        TextUsuario.setFont(new java.awt.Font("Cambria", 0, 18));
        TextUsuario.setText("Sr. Reaño");
        TextUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextUsuarioActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 18));
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("Hora :");

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Cambria", 0, 18));
        jTextField2.setText("12:23 P.M");

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 18));
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Fecha : ");

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Cambria", 0, 18));
        jTextField3.setText("07 de Diciembre del 2013");
        jTextField3.setPreferredSize(new java.awt.Dimension(155, 28));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 51, 102));
        jButton4.setFont(new java.awt.Font("Cambria", 0, 18));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reloj.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 51, 102));
        jButton5.setFont(new java.awt.Font("Cambria", 0, 18));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logout.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Cambria", 1, 18));
        lblTitulo.setForeground(new java.awt.Color(0, 51, 102));
        lblTitulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 1, true));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FECHAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 1, 14), new java.awt.Color(0, 51, 102))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 18));
        jLabel4.setText("Fecha inicio:");

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 18));
        jLabel6.setText("Fecha fin:");

        CalendarFechaInicio.setToolTipText("");
        CalendarFechaInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CalendarFechaInicio.setDateFormatString("yyyy-MM-dd"); // NOI18N

        CalendarFechaFin.setDateFormatString("yyyy-MM-dd"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CalendarFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CalendarFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CalendarFechaFin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel6)
                        .addComponent(CalendarFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BotonVentas.setBackground(new java.awt.Color(204, 204, 204));
        BotonVentas.setFont(new java.awt.Font("Cambria", 0, 18));
        BotonVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carrito_1.png"))); // NOI18N
        BotonVentas.setPreferredSize(new java.awt.Dimension(85, 67));
        BotonVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVentasActionPerformed(evt);
            }
        });

        BotonGastos.setBackground(new java.awt.Color(204, 204, 204));
        BotonGastos.setFont(new java.awt.Font("Cambria", 0, 18));
        BotonGastos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gastos_1.png"))); // NOI18N
        BotonGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGastosActionPerformed(evt);
            }
        });

        BotonAlmacen.setBackground(new java.awt.Color(204, 204, 204));
        BotonAlmacen.setFont(new java.awt.Font("Cambria", 0, 18));
        BotonAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/almacen_1.png"))); // NOI18N
        BotonAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAlmacenActionPerformed(evt);
            }
        });

        BotonAsistencia.setBackground(new java.awt.Color(204, 204, 204));
        BotonAsistencia.setFont(new java.awt.Font("Cambria", 0, 18));
        BotonAsistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/users_1.png"))); // NOI18N
        BotonAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAsistenciaActionPerformed(evt);
            }
        });

        BotonBarraVertical.setBackground(new java.awt.Color(204, 204, 204));
        BotonBarraVertical.setFont(new java.awt.Font("Cambria", 0, 18));
        BotonBarraVertical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verticales_1.png"))); // NOI18N
        BotonBarraVertical.setPreferredSize(new java.awt.Dimension(85, 67));
        BotonBarraVertical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBarraVerticalActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Cambria", 0, 16));
        jLabel10.setText("Ventas       Gastos        Almacén    Asis. Per.");

        BotonBarraHorizontal.setBackground(new java.awt.Color(204, 204, 204));
        BotonBarraHorizontal.setFont(new java.awt.Font("Cambria", 0, 18));
        BotonBarraHorizontal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/horizontal_1.png"))); // NOI18N
        BotonBarraHorizontal.setPreferredSize(new java.awt.Dimension(85, 67));
        BotonBarraHorizontal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBarraHorizontalActionPerformed(evt);
            }
        });

        BotonTorta.setBackground(new java.awt.Color(204, 204, 204));
        BotonTorta.setFont(new java.awt.Font("Cambria", 0, 18));
        BotonTorta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/torta_1.png"))); // NOI18N
        BotonTorta.setPreferredSize(new java.awt.Dimension(85, 67));
        BotonTorta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTortaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 921, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(BotonVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotonGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotonAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotonAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(10, 10, 10))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(BotonBarraVertical, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonBarraHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonTorta, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7)
                                .addGap(34, 34, 34))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextUsuario)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 20, Short.MAX_VALUE)
                        .addComponent(jLabel15)))
                .addGap(11, 11, 11)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BotonGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotonTorta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonBarraHorizontal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonBarraVertical, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                .addGap(310, 310, 310))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 973, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextUsuarioActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        BotonesComunes.ingresoAsistencia();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Sanguchito.sanguchito.removeAll();
        GeneracionReportes reportes=new GeneracionReportes();
        Sanguchito.sanguchito.add(reportes);
        try{
            reportes.setMaximum(true);
        }catch(Exception e){

        }
        reportes.show();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void BotonVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVentasActionPerformed
        ReporVentas tiporeporven=new ReporVentas();
        modulo = "ventas";
        
        CalendarFechaFin.setEnabled(true);
        CalendarFechaInicio.setEnabled(true);
        BotonBarraHorizontal.setEnabled(true);
        BotonBarraVertical.setEnabled(true);
        BotonTorta.setEnabled(true);
        
        Sanguchito.sanguchito.add(tiporeporven);
        try{
            tiporeporven.setMaximum(false);
        }catch(Exception e){

        }
        tiporeporven.show();
    }//GEN-LAST:event_BotonVentasActionPerformed

    private void BotonGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGastosActionPerformed
        // TODO add your handling code here:
        modulo = "gastos";
        CalendarFechaFin.setEnabled(true);
        CalendarFechaInicio.setEnabled(true);
        BotonBarraHorizontal.setEnabled(true);
        BotonBarraVertical.setEnabled(true);
        BotonTorta.setEnabled(true);
    }//GEN-LAST:event_BotonGastosActionPerformed

    private void BotonAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAlmacenActionPerformed
      
        ReporAlmacen tiporeporal=new ReporAlmacen();
        tiporeporal.CheckCategoria.setEnabled(false);
        tiporeporal.CheckProducto.setEnabled(false);
        tiporeporal.TextCategoria.setEnabled(false);
        tiporeporal.TextProducto.setEnabled(false);
        modulo = "almacen";
        CalendarFechaFin.setEnabled(true);
        CalendarFechaInicio.setEnabled(true);
        BotonBarraHorizontal.setEnabled(true);
        BotonBarraVertical.setEnabled(true);
        BotonTorta.setEnabled(true);
        Sanguchito.sanguchito.add(tiporeporal);
        try{
            tiporeporal.setMaximum(false);
        }catch(Exception e){

        }
        tiporeporal.show();
    }//GEN-LAST:event_BotonAlmacenActionPerformed

    private void BotonAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAsistenciaActionPerformed
        //Sanguchito.sanguchito.removeAll();
        AsisPersonal reportepersonal=new AsisPersonal();
        modulo = "personal";
        CalendarFechaFin.setEnabled(true);
        CalendarFechaInicio.setEnabled(true);
        BotonBarraHorizontal.setEnabled(true);
        BotonBarraVertical.setEnabled(true);
        BotonTorta.setEnabled(true);
        Sanguchito.sanguchito.add(reportepersonal);
        try{
            reportepersonal.setMaximum(false);
        }catch(Exception e){

        }
        reportepersonal.show();
    }//GEN-LAST:event_BotonAsistenciaActionPerformed

    private void BotonBarraVerticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBarraVerticalActionPerformed
        // TODO add your handling code here:
        Calendar jj = CalendarFechaInicio.getCalendar();
        String anho_i = Integer.toString(jj.get(Calendar.YEAR));
        String mesj_i = Integer.toString(jj.get(Calendar.MONTH));
        String diaj_i = Integer.toString(jj.get(Calendar.DATE));
        
        Calendar jo = CalendarFechaFin.getCalendar();
        String anho_f = Integer.toString(jo.get(Calendar.YEAR));
        String mesj_f = Integer.toString(jo.get(Calendar.MONTH));
        String diaj_f = Integer.toString(jj.get(Calendar.DATE));
        
        
        
        if (modulo.equals("ventas")) {
            if (TipoReporte.equals("ReporteDiario")) {
                if (opcion == 1) {
                    mostrar.reportdia(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), categoria, _anio, _mes, _dia, "1");
                }
                if (opcion == 2) {
                    mostrarp.reportdia(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), producto, _anio,_mes, _dia, "1");
                }
                if (opcion == 3) {
                    mostrarg.reportdia(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), _anio, _mes, _dia, "1");
                }
            }

            if (TipoReporte.equals("ReporteSemanal")){
                if (opcion == 1) {
                    mostrar.reportsemana(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), categoria,anho_i, mesj_i, diaj_i, diaj_f, "1");
                }
                if (opcion == 2) {
                    mostrarp.reportsemana(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), producto,anho_i, mesj_i, diaj_i, diaj_f, "1");
                }
                if (opcion == 3) {
                    mostrarg.reportsemana(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(),anho_i, mesj_i, diaj_i, diaj_f, "1");
                }
            }

            if (TipoReporte.equals("ReporteMensual")) {
                if (opcion == 1) {
                    mostrar.reportmes(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), categoria, _anio,_mes, "1");
                }
                if (opcion == 2) {
                    mostrarp.reportmes(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), producto, _anio,_mes, "1");

                }
                if (opcion == 3) {
                    mostrarg.reportmes(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), _anio,_mes,"1");

                }
            }

            if (TipoReporte.equals("ReporteAnual")) {
                if (opcion == 1) {
                    mostrar.reportanio(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), categoria,_anio, "1");
                }
                if (opcion == 2) {
                    mostrarp.reportanio(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), producto,_anio, "1");

                }
                if (opcion == 3) {
                    mostrarg.reportanio(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(),_anio, "1");

                }
            }

            if (TipoReporte.equals("ReportePeriodo")) {
                if (opcion == 1) {
                    mostrar.reportperiodo(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), categoria, anho_i+"-"+mesj_i+"-"+diaj_i, anho_f+"-"+mesj_f+"-"+diaj_f, "1");
                }
                if (opcion == 2) {
                    mostrarp.reportperiodo(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), producto, anho_i+"-"+mesj_i+"-"+diaj_i, anho_f+"-"+mesj_f+"-"+diaj_f, "1");

                }
                if (opcion == 3) {
                    
                    mostrarg.reportperiodo(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), anho_i+"-"+mesj_i+"-"+diaj_i, anho_f+"-"+mesj_f+"-"+diaj_f, "1");
                }
            }
        }

        //Fin de ventas
        if (modulo.equals("almacen")) {
            if (TipoReporte.equals("ReporteDiario")) {

                mostraral.reportdia(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), _anio, _mes, _dia, "1");

            }

            ////////////////
            if (TipoReporte.equals("ReporteSemanal")) {

                mostraral.reportsemana(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), anho_i,mesj_i,diaj_i,diaj_f, "1");

            }

            if (TipoReporte.equals("ReporteMensual")) {

                mostraral.reportmes(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), anho_i, mesj_i, "1");

            }

            if (TipoReporte.equals("ReporteAnual")) {

                mostraral.reportanio(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), anho_i, "1");

            }

            if (TipoReporte.equals("ReportePeriodo")) {

                mostraral.reportperiodo(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), anho_i, anho_f, mesj_i,mesj_f,diaj_i,diaj_f, "1");

            }
        }

        //Fin de almacen
        if (modulo.equals("gastos")) {
            if (TipoReporte.equals("ReporteDiario")) {
                mostrarga.reportdiagasto(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), _anio, _mes,_dia, "1");
            }

            ////////////////
            if (TipoReporte.equals("ReporteSemanal")) {
                mostrarga.reportsemana(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), anho_i,mesj_i, diaj_i,diaj_f, "1");
            }

            if (TipoReporte.equals("ReporteMensual")) {

                mostrarga.reportmes(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), anho_i, mesj_i, "1");

            }

            if (TipoReporte.equals("ReporteAnual")) {

                mostrarga.reportanio(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), anho_i, "1");

            }

            if (TipoReporte.equals("ReportePeriodo")) {

                mostrarga.reportperiodo(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), anho_i, anho_f, mesj_i ,mesj_f,diaj_i,diaj_f, "1");

            }
        }

        if (modulo.equals("personal")) {
            if (TipoReporte.equals("ReporteDiario")) {
                mostrarper.reportpersonal(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), nombre,_anio,_mes,_dia, "1");
            }

            ////////////////
            if (TipoReporte.equals("ReporteSemanal")) {
                mostrarper.reportpersonalsemana(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), nombre,anho_i,mesj_i,diaj_i,diaj_f, "1");
            }

            if (TipoReporte.equals("ReporteMensual")) {

                mostrarper.reportpersonalmes(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), nombre, anho_i,mesj_i, "1");

            }

            if (TipoReporte.equals("ReporteAnual")) {

                mostrarper.reportpersonalanio(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), nombre, anho_i, "1");

            }

            if (TipoReporte.equals("ReportePeriodo")) {

                mostrarper.reportpersonalperiodo(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), nombre, anho_i+"-"+mesj_i+"-"+diaj_i, anho_f+"-"+mesj_f+"-"+diaj_f, "1");

            }

        }
    }//GEN-LAST:event_BotonBarraVerticalActionPerformed

    private void BotonBarraHorizontalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBarraHorizontalActionPerformed
        // TODO add your handling code here:
        Calendar jj = CalendarFechaInicio.getCalendar();
        String anho_i = Integer.toString(jj.get(Calendar.YEAR));
        String mesj_i = Integer.toString(jj.get(Calendar.MONTH));
        String diaj_i = Integer.toString(jj.get(Calendar.DATE));
        
        Calendar jo = CalendarFechaFin.getCalendar();
        String anho_f = Integer.toString(jo.get(Calendar.YEAR));
        String mesj_f = Integer.toString(jo.get(Calendar.MONTH));
        String diaj_f = Integer.toString(jj.get(Calendar.DATE));
        
        if (modulo == "ventas") {
            if (TipoReporte == "ReporteDiario") {
                if (opcion == 1) {
                    mostrar.reportdia(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), categoria, _anio, _mes, _dia, "2");
                }
                if (opcion == 2) {
                    mostrarp.reportdia(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), producto, _anio, _mes,_dia, "2");
                }
                if (opcion == 3) {
                    mostrarg.reportdia(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(),_anio,_mes,_dia, "2");
                }
            }
            /////////////
            if (TipoReporte == "ReporteSemanal") {
                if (opcion == 1) {
                        mostrar.reportsemana(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), categoria, anho_i,mesj_i, diaj_i, diaj_f, "2");
                }
                if (opcion == 2) {
                    mostrarp.reportsemana(_dia+"/"+_mes+"/"+_anio   , TextUsuario.getText(), producto, anho_i,mesj_i, diaj_i, diaj_f, "2");
                }
                if (opcion == 3) {
                    mostrarg.reportsemana(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), anho_i,mesj_i, diaj_i, diaj_f, "2");
                }

            }

            if (TipoReporte == "ReporteMensual") {
                if (opcion == 1) {
                    mostrar.reportmes(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), categoria, anho_i,mesj_i, "2");
                }
                if (opcion == 2) {
                    mostrarp.reportmes(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), producto, anho_i,mesj_i, "2");

                }
                if (opcion == 3) {
                    mostrarg.reportmes(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(),anho_i,mesj_i, "2");

                }
            }

            if (TipoReporte == "ReporteAnual") {
                if (opcion == 1) {
                    mostrar.reportanio(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), categoria, anho_i, "2");
                }
                if (opcion == 2) {
                    mostrarp.reportanio(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), producto, anho_i, "2");

                }
                if (opcion == 3) {
                    mostrarg.reportanio(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), anho_i, "2");

                }
            }

            if (TipoReporte == "ReportePeriodo") {
                if (opcion == 1) {
                    mostrar.reportperiodo(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), categoria,anho_i+"-"+mesj_i+"-"+diaj_i, anho_f+"-"+mesj_f+"-"+diaj_f, "2");
                }
                if (opcion == 2) {
                    mostrarp.reportperiodo(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), producto, anho_i+"-"+mesj_i+"-"+diaj_i, anho_f+"-"+mesj_f+"-"+diaj_f, "2");

                }
                if (opcion == 3) {
                    mostrarg.reportperiodo(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), anho_i+"-"+mesj_i+"-"+diaj_i, anho_f+"-"+mesj_f+"-"+diaj_f, "2");
                }
            }
        }
        //Fin de ventas

        if (modulo == "almacen") {
            if (TipoReporte == "ReporteDiario") {

                mostraral.reportdia(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(),_anio,_mes,_dia, "2");

            }

            ////////////////
            if (TipoReporte == "ReporteSemanal") {

                mostraral.reportsemana(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), anho_i,mesj_i, diaj_i,diaj_f, "2");

            }

            if (TipoReporte == "ReporteMensual") {

                mostraral.reportmes(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), anho_i,mesj_i, "2");

            }

            if (TipoReporte == "ReporteAnual") {

                mostraral.reportanio(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), anho_i, "2");

            }

            if (TipoReporte == "ReportePeriodo") {

                mostraral.reportperiodo(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), anho_i,anho_f, mesj_i,mesj_f, diaj_i,diaj_f,"2");

            }
        }

        if (modulo == "gastos") {
            if (TipoReporte == "ReporteDiario") {
                mostrarga.reportdiagasto(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), _anio,_mes,_dia, "2");
            }

            ////////////////
            if (TipoReporte == "ReporteSemanal") {
                mostrarga.reportsemana(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(),anho_i, mesj_i, diaj_i, diaj_f, "2");
            }

            if (TipoReporte == "ReporteMensual") {

                mostrarga.reportmes(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(),anho_i,mesj_i, "2");

            }

            if (TipoReporte == "ReporteAnual") {

                mostrarg.reportanio(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(),anho_i, "2");

            }

            if (TipoReporte == "ReportePeriodo") {

                mostrarga.reportperiodo(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(),anho_i, anho_f,mesj_i,mesj_f,diaj_i,diaj_f, "2");

            }
        }

        if (modulo == "personal") {
            if (TipoReporte == "ReporteDiario") {
                mostrarper.reportpersonal(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), nombre, _anio,_mes,_dia, "2");
            }

            ////////////////
            if (TipoReporte == "ReporteSemanal") {
                mostrarper.reportpersonalsemana(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), nombre, anho_i, mesj_i,diaj_i,diaj_f, "2");
            }

            if (TipoReporte == "ReporteMensual") {

                mostrarper.reportpersonalmes(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), nombre, anho_i, mesj_i, "2");

            }

            if (TipoReporte == "ReporteAnual") {

                mostrarper.reportpersonalanio(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), nombre, anho_i, "2");

            }

            if (TipoReporte == "ReportePeriodo") {

                mostrarper.reportpersonalperiodo(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), nombre, anho_i+"-"+mesj_i+"-"+diaj_i, anho_f+"-"+mesj_f+"-"+diaj_f, "2");

            }

        }
    }//GEN-LAST:event_BotonBarraHorizontalActionPerformed

    private void BotonTortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTortaActionPerformed
        // TODO add your handling code here:
        Calendar jj = CalendarFechaInicio.getCalendar();
        String anho_i = Integer.toString(jj.get(Calendar.YEAR));
        String mesj_i = Integer.toString(jj.get(Calendar.MONTH));
        String diaj_i = Integer.toString(jj.get(Calendar.DATE));
        
        Calendar jo = CalendarFechaFin.getCalendar();
        String anho_f = Integer.toString(jo.get(Calendar.YEAR));
        String mesj_f = Integer.toString(jo.get(Calendar.MONTH));
        String diaj_f = Integer.toString(jj.get(Calendar.DATE));
        
         if (modulo == "ventas") {
            if (TipoReporte == "ReporteDiario") {
                if (opcion == 1) {
                    mostrar.reportdia(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), categoria, _anio,_mes,_dia, "3");
                }
                if (opcion == 2) {
                    mostrarp.reportdia(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), producto, _anio,_mes,_dia, "3");
                }
                if (opcion == 3) {
                    mostrarg.reportdia(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), _anio,_mes,_dia, "3");
                }
            }
            ////////////////////////
            if (TipoReporte == "ReporteSemanal") {
                if (opcion == 1) {
                    mostrar.reportsemana(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), categoria, anho_i, mesj_i,diaj_i, diaj_f, "3");

                }
                if (opcion == 2) {
                    mostrarp.reportsemana(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), producto, anho_i, mesj_i,diaj_i, diaj_f, "3");
                }
                if (opcion == 3) {
                    mostrarg.reportsemana(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), anho_i, mesj_i,diaj_i, diaj_f, "3");

                }
            }

            if (TipoReporte == "ReporteMensual") {
                if (opcion == 1) {
                    mostrar.reportmes(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), categoria,anho_i, mesj_i, "3");
                }
                if (opcion == 2) {
                    mostrarp.reportmes(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), producto, anho_i, mesj_i, "3");

                }
                if (opcion == 3) {
                    mostrarg.reportmes(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(),anho_i, mesj_i, "3");
                }
            }

            if (TipoReporte == "ReporteAnual") {
                if (opcion == 1) {
                    mostrar.reportanio(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), categoria,anho_i, "3");
                }
                if (opcion == 2) {
                    mostrarp.reportanio(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), producto, anho_i, "3");

                }
                if (opcion == 3) {
                    mostrarg.reportanio(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), anho_i, "3");

                }
            }

            if (TipoReporte == "ReportePeriodo") {
                if (opcion == 1) {
                    mostrar.reportperiodo(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), categoria,anho_i+"-"+mesj_i+"-"+diaj_i, anho_f+"-"+mesj_f+"-"+diaj_f, "3");
                }
                if (opcion == 2) {
                    mostrarp.reportperiodo(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), producto, anho_i+"-"+mesj_i+"-"+diaj_i, anho_f+"-"+mesj_f+"-"+diaj_f, "3");

                }
                if (opcion == 3) {
                    mostrarg.reportperiodo(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), anho_i+"-"+mesj_i+"-"+diaj_i, anho_f+"-"+mesj_f+"-"+diaj_f, "3");
                }
            }
        }
        //Fin de ventas

        if (modulo == "almacen") {
            if (TipoReporte == "ReporteDiario") {

                mostraral.reportdia(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(),_anio,_mes,_dia, "3");

            }

            ////////////////
            if (TipoReporte == "ReporteSemanal") {

                mostraral.reportsemana(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), anho_i, mesj_i,diaj_i,diaj_f, "3");

            }

            if (TipoReporte == "ReporteMensual") {

                mostraral.reportmes(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(),anho_i,mesj_i, "3");

            }

            if (TipoReporte == "ReporteAnual") {

                mostraral.reportanio(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(),anho_i, "3");

            }

            if (TipoReporte == "ReportePeriodo") {

                mostraral.reportperiodo(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), anho_i,anho_f,mesj_i,mesj_f, diaj_i,diaj_f, "3");

            }
        }

        if (modulo == "gastos") {
            if (TipoReporte == "ReporteDiario") {
                mostrarga.reportdiagasto(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(),_anio,_mes,_dia, "3");
            }

            ////////////////
            if (TipoReporte == "ReporteSemanal") {
                mostrarga.reportsemana(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), anho_i,mesj_i,diaj_i,diaj_f, "3");
            }

            if (TipoReporte == "ReporteMensual") {

                mostrarga.reportmes(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(),anho_i,mesj_i, "3");

            }

            if (TipoReporte == "ReporteAnual") {

                mostrarga.reportanio(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(),anho_i, "3");

            }

            if (TipoReporte == "ReportePeriodo") {

                mostrarga.reportperiodo(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), anho_i, anho_f, mesj_i,mesj_f,diaj_i, diaj_f, "3");

            }
        }

        if (modulo == "personal") {
            if (TipoReporte == "ReporteDiario") {
                mostrarper.reportpersonal(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), nombre, _anio,_mes,_dia, "3");
            }

            ////////////////
            if (TipoReporte == "ReporteSemanal") {
                mostrarper.reportpersonalsemana(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), nombre, anho_i,mesj_i,diaj_i,diaj_f, "3");
            }

            if (TipoReporte == "ReporteMensual") {

                mostrarper.reportpersonalmes(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), nombre, anho_i,mesj_i, "3");

            }

            if (TipoReporte == "ReporteAnual") {

                mostrarper.reportpersonalanio(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), nombre,anho_i, "3");

            }

            if (TipoReporte == "ReportePeriodo") {

                mostrarper.reportpersonalperiodo(_dia+"/"+_mes+"/"+_anio, TextUsuario.getText(), nombre, anho_i+"-"+mesj_i+"-"+diaj_i, anho_f+"-"+mesj_f+"-"+diaj_f, "3");

            }

        }
    }//GEN-LAST:event_BotonTortaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAlmacen;
    private javax.swing.JButton BotonAsistencia;
    public javax.swing.JButton BotonBarraHorizontal;
    public javax.swing.JButton BotonBarraVertical;
    private javax.swing.JButton BotonGastos;
    public javax.swing.JButton BotonTorta;
    private javax.swing.JButton BotonVentas;
    public com.toedter.calendar.JDateChooser CalendarFechaFin;
    public com.toedter.calendar.JDateChooser CalendarFechaInicio;
    private javax.swing.JTextField TextUsuario;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    public static javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
