/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.epissoft.sanguchito.vista.reportes;

/**
 *
 * @author Roger
 */
public class ReporAlmacen extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReporAlmacen
     */
    GeneracionReportes2 pasar = new GeneracionReportes2();
    public ReporAlmacen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        Boton = new javax.swing.JButton();
        CheckCategoria = new javax.swing.JCheckBox();
        TextCategoria = new javax.swing.JTextField();
        CheckProducto = new javax.swing.JCheckBox();
        TextProducto = new javax.swing.JTextField();
        CheckGeneral = new javax.swing.JCheckBox();

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setText("TIPOS DE REPORTES DE ALMACEN");

        Boton.setBackground(new java.awt.Color(0, 51, 102));
        Boton.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        Boton.setForeground(new java.awt.Color(255, 255, 255));
        Boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logout.png"))); // NOI18N
        Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActionPerformed(evt);
            }
        });

        CheckCategoria.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        CheckCategoria.setText("Por categoría");
        CheckCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckCategoriaActionPerformed(evt);
            }
        });

        TextCategoria.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        CheckProducto.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        CheckProducto.setText("Por producto");
        CheckProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckProductoActionPerformed(evt);
            }
        });

        TextProducto.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        CheckGeneral.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        CheckGeneral.setText("General");
        CheckGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckGeneralActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckGeneral)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(CheckProducto)
                                .addGap(18, 18, 18)
                                .addComponent(TextProducto))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(CheckCategoria)
                                .addGap(18, 18, 18)
                                .addComponent(TextCategoria))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                .addComponent(Boton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Boton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CheckCategoria)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TextCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckProducto)
                    .addComponent(TextProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CheckGeneral)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckGeneralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckGeneralActionPerformed

    private void CheckProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckProductoActionPerformed

    private void CheckCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckCategoriaActionPerformed

    private void BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActionPerformed
        if(CheckCategoria.isSelected()==true)
        {
          pasar.categoria=TextCategoria.getText();
          pasar.producto=" ";
          pasar.opcion=1;
        }
          
        
        if(CheckProducto.isSelected()==true)
        {
           
            pasar.producto=TextProducto.getText();
            pasar.categoria=" ";
            pasar.opcion=2;
            
        }
        if(CheckGeneral.isSelected()==true)
        {
            pasar.opcion=3;
        }
          
        dispose();
    }//GEN-LAST:event_BotonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton;
    public javax.swing.JCheckBox CheckCategoria;
    private javax.swing.JCheckBox CheckGeneral;
    public javax.swing.JCheckBox CheckProducto;
    public javax.swing.JTextField TextCategoria;
    public javax.swing.JTextField TextProducto;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
