package com.epissoft.sanguchito.vista.menuprincipal;

import com.epissoft.sanguchito.vista.*;
import com.epissoft.sanguchito.vista.almacencategoria.ListaCategoriasAlmacen;
import com.epissoft.sanguchito.vista.cargos.ListaCargos;
import com.epissoft.sanguchito.vista.empleados.BuscarEmpleado;
import com.epissoft.sanguchito.vista.empleados.BuscarUsuario;
import com.epissoft.sanguchito.vista.extracategoria.ListaCategoriasExtras;
import com.epissoft.sanguchito.vista.gastos.ListaTipoGasto;
import com.epissoft.sanguchito.vista.productosofrecidoscategoria.ListaCategoriasProductosOfrecidos;
import com.epissoft.sanguchito.vista.proveedores.ListaProveedores;
import com.epissoft.sanguchito.vista.reportes.GeneracionReportes;
import com.epissoft.sanguchito.vista.turno.ListaTurnos;
import com.epissoft.sanguchito.vista.unidades.ListaUnidades;
import com.epissoft.sanguchito.vista.utilitarios.ActualizarReloj;
import com.epissoft.sanguchito.vista.utilitarios.BotonesComunes;
import com.epissoft.sanguchito.vista.utilitarios.CargarFecha;

public class MenuAdministrador extends javax.swing.JInternalFrame {

    public MenuAdministrador() {
        initComponents();
        tUsuario.setText(ManejoSesion.getUsuario());
        ActualizarReloj actualizar=new ActualizarReloj(tHora);
        CargarFecha.cargarFechaActual(tFecha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lBienvenida = new javax.swing.JLabel();
        lUsuario = new javax.swing.JLabel();
        tUsuario = new javax.swing.JTextField();
        lHora = new javax.swing.JLabel();
        tHora = new javax.swing.JTextField();
        lFecha = new javax.swing.JLabel();
        tFecha = new javax.swing.JTextField();
        bAsistencia = new javax.swing.JButton();
        bCerrarSesion = new javax.swing.JButton();
        lTitulo = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Productos = new javax.swing.JPanel();
        bGestionProductos = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bGestionExtras = new javax.swing.JButton();
        Almacen = new javax.swing.JPanel();
        bGestionUnidades = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        bGestionAlmacen = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        bGestionProveedores = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Personal = new javax.swing.JPanel();
        bGestionTurnos = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        bGestionCargos = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        bGestionPersonal = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        bGestionUsuarios = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        Otros = new javax.swing.JPanel();
        bGestionGastos = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        bGestionReportes = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        bAjustes = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 186));

        lBienvenida.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lBienvenida.setForeground(new java.awt.Color(0, 51, 102));
        lBienvenida.setText("Bienvenido  a  SanGuchitoSoft");

        lUsuario.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lUsuario.setForeground(new java.awt.Color(0, 51, 102));
        lUsuario.setText(" Usuario :");

        tUsuario.setEditable(false);
        tUsuario.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        tUsuario.setText("Sr. Reaño");
        tUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tUsuarioActionPerformed(evt);
            }
        });

        lHora.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lHora.setForeground(new java.awt.Color(0, 51, 102));
        lHora.setText("Hora :");

        tHora.setEditable(false);
        tHora.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        tHora.setText("12:23 P.M");

        lFecha.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lFecha.setForeground(new java.awt.Color(0, 51, 102));
        lFecha.setText("Fecha : ");

        tFecha.setEditable(false);
        tFecha.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        tFecha.setText("07 de Diciembre del 2013");
        tFecha.setPreferredSize(new java.awt.Dimension(155, 28));
        tFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFechaActionPerformed(evt);
            }
        });

        bAsistencia.setBackground(new java.awt.Color(0, 51, 102));
        bAsistencia.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        bAsistencia.setForeground(new java.awt.Color(255, 255, 255));
        bAsistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reloj.png"))); // NOI18N
        bAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAsistenciaActionPerformed(evt);
            }
        });

        bCerrarSesion.setBackground(new java.awt.Color(0, 51, 102));
        bCerrarSesion.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        bCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        bCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logout.png"))); // NOI18N
        bCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCerrarSesionActionPerformed(evt);
            }
        });

        lTitulo.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lTitulo.setForeground(new java.awt.Color(0, 51, 102));
        lTitulo.setText("MENU PRINCIPAL");
        lTitulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 1, true));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N

        Productos.setBackground(new java.awt.Color(255, 255, 255));
        Productos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 0, 18), new java.awt.Color(51, 51, 255))); // NOI18N

        bGestionProductos.setBackground(new java.awt.Color(204, 204, 204));
        bGestionProductos.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        bGestionProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gestionProductosOfrecidos.png"))); // NOI18N
        bGestionProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGestionProductosActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel10.setText("<html><center><p>Gestión de Productos</p><p>Ofrecidos</p></center></html>");

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel4.setText("Gestión de Extras");

        bGestionExtras.setBackground(new java.awt.Color(204, 204, 204));
        bGestionExtras.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        bGestionExtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gestionExtras.png"))); // NOI18N
        bGestionExtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGestionExtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProductosLayout = new javax.swing.GroupLayout(Productos);
        Productos.setLayout(ProductosLayout);
        ProductosLayout.setHorizontalGroup(
            ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductosLayout.createSequentialGroup()
                .addGroup(ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductosLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(bGestionProductos))
                    .addGroup(ProductosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(ProductosLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(bGestionExtras)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ProductosLayout.setVerticalGroup(
            ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductosLayout.createSequentialGroup()
                .addGroup(ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bGestionProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bGestionExtras, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)))
        );

        Almacen.setBackground(new java.awt.Color(255, 255, 255));
        Almacen.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Almacen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 0, 18), new java.awt.Color(51, 51, 255))); // NOI18N

        bGestionUnidades.setBackground(new java.awt.Color(204, 204, 204));
        bGestionUnidades.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        bGestionUnidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gastos.png"))); // NOI18N
        bGestionUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGestionUnidadesActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel8.setText("Gestión de Unidades");

        bGestionAlmacen.setBackground(new java.awt.Color(204, 204, 204));
        bGestionAlmacen.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        bGestionAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gestionAlmacen.png"))); // NOI18N
        bGestionAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGestionAlmacenActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel11.setText("Gestión de Almacén");

        bGestionProveedores.setBackground(new java.awt.Color(204, 204, 204));
        bGestionProveedores.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        bGestionProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gestionProveedores.png"))); // NOI18N
        bGestionProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGestionProveedoresActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel9.setText("Gestión de Poveedores");

        javax.swing.GroupLayout AlmacenLayout = new javax.swing.GroupLayout(Almacen);
        Almacen.setLayout(AlmacenLayout);
        AlmacenLayout.setHorizontalGroup(
            AlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlmacenLayout.createSequentialGroup()
                .addGroup(AlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(AlmacenLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(bGestionUnidades)))
                .addGroup(AlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AlmacenLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(bGestionAlmacen))
                    .addGroup(AlmacenLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(AlmacenLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(bGestionProveedores)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AlmacenLayout.setVerticalGroup(
            AlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlmacenLayout.createSequentialGroup()
                .addGroup(AlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AlmacenLayout.createSequentialGroup()
                        .addComponent(bGestionProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addGroup(AlmacenLayout.createSequentialGroup()
                        .addComponent(bGestionAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(AlmacenLayout.createSequentialGroup()
                        .addComponent(bGestionUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Personal.setBackground(new java.awt.Color(255, 255, 255));
        Personal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 0, 18), new java.awt.Color(51, 51, 255))); // NOI18N

        bGestionTurnos.setBackground(new java.awt.Color(204, 204, 204));
        bGestionTurnos.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        bGestionTurnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gestionTurnos.png"))); // NOI18N
        bGestionTurnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGestionTurnosActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel18.setText("Gestión de Turnos");

        bGestionCargos.setBackground(new java.awt.Color(204, 204, 204));
        bGestionCargos.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        bGestionCargos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gestionUsuario.png"))); // NOI18N
        bGestionCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGestionCargosActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel19.setText("Gestión de Cargos");

        bGestionPersonal.setBackground(new java.awt.Color(204, 204, 204));
        bGestionPersonal.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        bGestionPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gestionPersonal.png"))); // NOI18N
        bGestionPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGestionPersonalActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel20.setText("Gestión de Personal");

        bGestionUsuarios.setBackground(new java.awt.Color(204, 204, 204));
        bGestionUsuarios.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        bGestionUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gestionPromociones.png"))); // NOI18N
        bGestionUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGestionUsuariosActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel21.setText("Gestión de Usuarios");

        javax.swing.GroupLayout PersonalLayout = new javax.swing.GroupLayout(Personal);
        Personal.setLayout(PersonalLayout);
        PersonalLayout.setHorizontalGroup(
            PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PersonalLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(bGestionTurnos))
                    .addComponent(jLabel18))
                .addGap(41, 41, 41)
                .addGroup(PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PersonalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bGestionCargos)
                        .addGap(13, 13, 13)))
                .addGap(28, 28, 28)
                .addGroup(PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addGroup(PersonalLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(bGestionPersonal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PersonalLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(bGestionUsuarios)))
                .addContainerGap())
        );
        PersonalLayout.setVerticalGroup(
            PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PersonalLayout.createSequentialGroup()
                .addComponent(bGestionUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addGroup(PersonalLayout.createSequentialGroup()
                        .addComponent(bGestionCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(PersonalLayout.createSequentialGroup()
                        .addComponent(bGestionTurnos, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)))
                .addGroup(PersonalLayout.createSequentialGroup()
                    .addComponent(bGestionPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(8, 8, 8)
                    .addComponent(jLabel20)))
        );

        Otros.setBackground(new java.awt.Color(255, 255, 255));
        Otros.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Otros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 0, 18), new java.awt.Color(51, 51, 255))); // NOI18N

        bGestionGastos.setBackground(new java.awt.Color(204, 204, 204));
        bGestionGastos.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        bGestionGastos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gestionGastos.png"))); // NOI18N
        bGestionGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGestionGastosActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel12.setText("Gestión de Gastos");

        bGestionReportes.setBackground(new java.awt.Color(204, 204, 204));
        bGestionReportes.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        bGestionReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gestionReportes.png"))); // NOI18N
        bGestionReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGestionReportesActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel13.setText("Reportes");

        bAjustes.setBackground(new java.awt.Color(204, 204, 204));
        bAjustes.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        bAjustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gestionAjustes.png"))); // NOI18N
        bAjustes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAjustesActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel17.setText("Ajustes");

        javax.swing.GroupLayout OtrosLayout = new javax.swing.GroupLayout(Otros);
        Otros.setLayout(OtrosLayout);
        OtrosLayout.setHorizontalGroup(
            OtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OtrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OtrosLayout.createSequentialGroup()
                        .addComponent(bGestionGastos)
                        .addGap(10, 10, 10)))
                .addGroup(OtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OtrosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(bGestionReportes)
                        .addGap(61, 61, 61))
                    .addGroup(OtrosLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(OtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OtrosLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(31, 31, 31))
                    .addComponent(bAjustes, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(21, 21, 21))
        );
        OtrosLayout.setVerticalGroup(
            OtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OtrosLayout.createSequentialGroup()
                .addGroup(OtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bGestionReportes)
                    .addComponent(bGestionGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)))
            .addGroup(OtrosLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(bAjustes, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 916, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lHora, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tHora, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lBienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(2, 2, 2)
                                        .addComponent(bAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(bCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Personal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Almacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Otros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lBienvenida)
                                .addGap(36, 36, 36)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tHora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tUsuario)
                                .addComponent(lFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lHora, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel15))
                .addGap(11, 11, 11)
                .addComponent(lTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Productos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Almacen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Personal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Otros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(299, 299, 299))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 973, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCerrarSesionActionPerformed
       BotonesComunes.deslogear();
    }//GEN-LAST:event_bCerrarSesionActionPerformed

    private void bAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAsistenciaActionPerformed
        BotonesComunes.ingresoAsistencia();
    }//GEN-LAST:event_bAsistenciaActionPerformed

    private void tFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFechaActionPerformed

    private void tUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tUsuarioActionPerformed

    private void bGestionProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGestionProductosActionPerformed
        Sanguchito.sanguchito.removeAll();
        ListaCategoriasProductosOfrecidos categoriasProductosOfrecidos=new ListaCategoriasProductosOfrecidos();
        Sanguchito.sanguchito.add(categoriasProductosOfrecidos);
        try{
            categoriasProductosOfrecidos.setMaximum(true);
        }catch(Exception e){

        }
        categoriasProductosOfrecidos.show();
    }//GEN-LAST:event_bGestionProductosActionPerformed

    private void bGestionExtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGestionExtrasActionPerformed
        Sanguchito.sanguchito.removeAll();
        ListaCategoriasExtras extras=new ListaCategoriasExtras();
        Sanguchito.sanguchito.add(extras);
        try{
            extras.setMaximum(true);
        }catch(Exception e){

        }
        extras.show();
    }//GEN-LAST:event_bGestionExtrasActionPerformed

    private void bGestionUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGestionUnidadesActionPerformed
        Sanguchito.sanguchito.removeAll();
        ListaUnidades unidades=new ListaUnidades();
        Sanguchito.sanguchito.add(unidades);
        try{
            unidades.setMaximum(false);
        }catch(Exception e){

        }
        unidades.show();
    }//GEN-LAST:event_bGestionUnidadesActionPerformed

    private void bGestionAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGestionAlmacenActionPerformed
        Sanguchito.sanguchito.removeAll();
        ListaCategoriasAlmacen categoriasAlmacen=new ListaCategoriasAlmacen();
        Sanguchito.sanguchito.add(categoriasAlmacen);
        try{
            categoriasAlmacen.setMaximum(true);
        }catch(Exception e){

        }
        categoriasAlmacen.show();
    }//GEN-LAST:event_bGestionAlmacenActionPerformed

    private void bGestionGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGestionGastosActionPerformed
        Sanguchito.sanguchito.removeAll();
        ListaTipoGasto categoriasAlmacen;
        categoriasAlmacen = new ListaTipoGasto();
        Sanguchito.sanguchito.add(categoriasAlmacen);
        try{
            categoriasAlmacen.setMaximum(true);
        }catch(Exception e){

        }
        categoriasAlmacen.show();
    }//GEN-LAST:event_bGestionGastosActionPerformed

    private void bGestionTurnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGestionTurnosActionPerformed
        Sanguchito.sanguchito.removeAll();
        ListaTurnos menu=new ListaTurnos();
        Sanguchito.sanguchito.add(menu);
        try{
            menu.setMaximum(true);
        }catch(Exception e){

        }
        menu.show();
    }//GEN-LAST:event_bGestionTurnosActionPerformed

    private void bGestionCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGestionCargosActionPerformed
        Sanguchito.sanguchito.removeAll();
        ListaCargos opcion=new ListaCargos();
        Sanguchito.sanguchito.add(opcion);
        try{
            opcion.setMaximum(true);
        }catch(Exception e){

        }
        opcion.show();
    }//GEN-LAST:event_bGestionCargosActionPerformed

    private void bGestionPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGestionPersonalActionPerformed
        // TODO add your handling code here:
        Sanguchito.sanguchito.removeAll();
        BuscarEmpleado empleado=new BuscarEmpleado();
        Sanguchito.sanguchito.add(empleado);
        try{
            empleado.setMaximum(true);
        }catch(Exception e){

        }
        empleado.show();
    }//GEN-LAST:event_bGestionPersonalActionPerformed

    private void bGestionUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGestionUsuariosActionPerformed
        Sanguchito.sanguchito.removeAll();
        BuscarUsuario opcion=new BuscarUsuario();
        Sanguchito.sanguchito.add(opcion);
        try{
            opcion.setMaximum(true);
        }catch(Exception e){

        }
        opcion.show();
    }//GEN-LAST:event_bGestionUsuariosActionPerformed

    private void bGestionProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGestionProveedoresActionPerformed
        Sanguchito.sanguchito.removeAll();
        ListaProveedores opcion=new ListaProveedores();
        Sanguchito.sanguchito.add(opcion);
        try{
            opcion.setMaximum(true);
        }catch(Exception e){

        }
        opcion.show();
    }//GEN-LAST:event_bGestionProveedoresActionPerformed

    private void bAjustesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAjustesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bAjustesActionPerformed

    private void bGestionReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGestionReportesActionPerformed
        Sanguchito.sanguchito.removeAll();
        GeneracionReportes reportes2=new GeneracionReportes();
        Sanguchito.sanguchito.add(reportes2);
        try{
            reportes2.setMaximum(true);
        }catch(Exception e){

        }
        reportes2.show();
    }//GEN-LAST:event_bGestionReportesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Almacen;
    private javax.swing.JPanel Otros;
    private javax.swing.JPanel Personal;
    private javax.swing.JPanel Productos;
    private javax.swing.JButton bAjustes;
    private javax.swing.JButton bAsistencia;
    private javax.swing.JButton bCerrarSesion;
    private javax.swing.JButton bGestionAlmacen;
    private javax.swing.JButton bGestionCargos;
    private javax.swing.JButton bGestionExtras;
    private javax.swing.JButton bGestionGastos;
    private javax.swing.JButton bGestionPersonal;
    private javax.swing.JButton bGestionProductos;
    private javax.swing.JButton bGestionProveedores;
    private javax.swing.JButton bGestionReportes;
    private javax.swing.JButton bGestionTurnos;
    private javax.swing.JButton bGestionUnidades;
    private javax.swing.JButton bGestionUsuarios;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lBienvenida;
    private javax.swing.JLabel lFecha;
    private javax.swing.JLabel lHora;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JLabel lUsuario;
    private javax.swing.JTextField tFecha;
    private javax.swing.JTextField tHora;
    private javax.swing.JTextField tUsuario;
    // End of variables declaration//GEN-END:variables

}
