CREATE TABLE almacen (IngCod INTEGER NOT NULL, AlmCant INTEGER, PRIMARY KEY (IngCod));
CREATE TABLE cierre_caja (AperCajCod INTEGER NOT NULL, CierCajFecAni INTEGER, CierCajFecDia INTEGER, CierCajFecMes INTEGER, CierCajHor TIME, CierCajObs VARCHAR(255), CierFacFin INTEGER, CierMont FLOAT, PRIMARY KEY (AperCajCod));
CREATE TABLE egreso_kardex (KarCod INTEGER NOT NULL, CantProdAlm INTEGER, PRIMARY KEY (KarCod));
CREATE TABLE unidad_medida (UniMedCod  SERIAL NOT NULL, UniMedDes VARCHAR(255), UniMedEst BOOLEAN, PRIMARY KEY (UniMedCod));
CREATE TABLE cargo (CarCod  SERIAL NOT NULL, CarDes VARCHAR(255), CarEst BOOLEAN, CarObs VARCHAR(255), PRIMARY KEY (CarCod));
CREATE TABLE tipo_facturacion (TipFacCod  SERIAL NOT NULL, TipFacDes VARCHAR(255), TipFacEst BOOLEAN, PRIMARY KEY (TipFacCod));
CREATE TABLE tipo_gasto (TipGasCod INTEGER NOT NULL, TipGasDes VARCHAR(255), TipGasEst VARCHAR(255), PRIMARY KEY (TipGasCod));
CREATE TABLE categoria_producto (CatProdCod  SERIAL NOT NULL, CatProdDes VARCHAR(255), CatProdEst BOOLEAN, CatProdImg VARCHAR(255), PRIMARY KEY (CatProdCod));
CREATE TABLE categoria_extra (CatExtCod  SERIAL NOT NULL, CatExtDes VARCHAR(255), CatExtEst BOOLEAN, CatExtImg VARCHAR(255), CatExtNom VARCHAR(255), PRIMARY KEY (CatExtCod));
CREATE TABLE kardex (KarCod  SERIAL NOT NULL, KarFecAnio INTEGER, KarFecDia INTEGER, KarFecMes INTEGER, ProdAlmCod INTEGER, PRIMARY KEY (KarCod));
CREATE TABLE tipousuario (TipUsuCod INTEGER NOT NULL, TipUsuDes VARCHAR(255), TipUsuNom VARCHAR(255), PRIMARY KEY (TipUsuCod));
CREATE TABLE proveedor (ProvRuc VARCHAR(255) NOT NULL, ProvApeMat VARCHAR(255), ProvApePat VARCHAR(255), ProvEst BOOLEAN, ProvMail VARCHAR(255), ProvNom VARCHAR(255), ProvRazSoc VARCHAR(255), ProvTel INTEGER, PRIMARY KEY (ProvRuc));
CREATE TABLE registro_falta (RegFaltaCod INTEGER NOT NULL, RegFalFecAnio INTEGER, RegFalFecDia INTEGER, RegFalFecMes INTEGER, RegFaltHor TIME, EmpDni INTEGER, TipFalCod INTEGER, PRIMARY KEY (RegFaltaCod));
CREATE TABLE tipo_falta (TipFalCod  SERIAL NOT NULL, TipFalDes VARCHAR(255), TipFalEst BOOLEAN, PRIMARY KEY (TipFalCod));
CREATE TABLE tipo_cliente (TipClieCod  SERIAL NOT NULL, TipClieDes VARCHAR(255), TipClieEst BOOLEAN, PRIMARY KEY (TipClieCod));
CREATE TABLE apertura_caja (AperCajCod  SERIAL NOT NULL, AperCajFecAni INTEGER, AperCajFecDia INTEGER, AperCajFecMes INTEGER, AperCajHor TIME, AperCajObs VARCHAR(255), AperFacIni INTEGER, AperMontIni FLOAT, UsuCod INTEGER, PRIMARY KEY (AperCajCod));
CREATE TABLE facturacion (FacCod  SERIAL NOT NULL, FacDesc FLOAT, FacFecAnio INTEGER, FacFecDia INTEGER, FacFecMes INTEGER, FacHor TIME, FacObs VARCHAR(255), FacTot FLOAT, ClieDni INTEGER, TipFacCod INTEGER, UsuCod INTEGER, PRIMARY KEY (FacCod));
CREATE TABLE producto (ProCod  SERIAL NOT NULL, ProAlmCod INTEGER, ProDes VARCHAR(255), ProEst BOOLEAN, ProImg VARCHAR(255), ProPreCar FLOAT, ProPreSol FLOAT, CatProdCod INTEGER, PRIMARY KEY (ProCod));
CREATE TABLE turno (TurCod  SERIAL NOT NULL, TurDes VARCHAR(255), TurEst BOOLEAN, TurHorFin TIME, TurHorIni TIME, PRIMARY KEY (TurCod));
CREATE TABLE facturacion_detalle (FacDetSec INTEGER NOT NULL, FacDetDesctProm INTEGER, FacDetPrec FLOAT, FacCod INTEGER, ProCod INTEGER, PRIMARY KEY (FacDetSec));
CREATE TABLE promociones (PromCod INTEGER NOT NULL, PromEst BOOLEAN, PromPorDesc FLOAT, ProCod INTEGER, PRIMARY KEY (PromCod));
CREATE TABLE extras (ExtCod  SERIAL NOT NULL, ExtDes VARCHAR(255), ExtEst BOOLEAN, ExtPrecSol FLOAT, ExtPrecSolCar FLOAT, ProAlmCod INTEGER, CatExtCod INTEGER, PRIMARY KEY (ExtCod));
CREATE TABLE empleado (EmpDni INTEGER NOT NULL, EmpApeMat VARCHAR(255), EmpApePat VARCHAR(255), EmpDir VARCHAR(255), EmpDirDis VARCHAR(255), EmpEst BOOLEAN, EmpNom VARCHAR(255), EmpSuel FLOAT, EmpTel1 INTEGER, EmpTel2 INTEGER, CarCod INTEGER, TurCod INTEGER, PRIMARY KEY (EmpDni));
CREATE TABLE gastos (GasCod  SERIAL NOT NULL, GasAnio INTEGER, GasDes VARCHAR(255), GasDia INTEGER, GasMes INTEGER, GasNBol INTEGER, GasNumDoc INTEGER, GasTot FLOAT, EmpDni INTEGER, ProvRuc VARCHAR(255), TipDocCod INTEGER, TipGasCod INTEGER, PRIMARY KEY (GasCod));
CREATE TABLE tipo_documento (TipDocCod  SERIAL NOT NULL, TipDocDes VARCHAR(255), PRIMARY KEY (TipDocCod));
CREATE TABLE ingreso_kardex (KarCod INTEGER NOT NULL, CantProdAlm INTEGER, PrecProdAlm FLOAT, GasCod INTEGER, PRIMARY KEY (KarCod));
CREATE TABLE producto_almacen (ProdAlmCod  SERIAL NOT NULL, ProAlmImg VARCHAR(255), ProdAlmCant FLOAT, ProdAlmDes VARCHAR(255), ProdAlmEst BOOLEAN, CatProdAlmCod INTEGER, UniMedCod INTEGER, PRIMARY KEY (ProdAlmCod));
CREATE TABLE categoria_producto_almacen (CatProdAlmCod  SERIAL NOT NULL, CatProdAlmDes VARCHAR(255), CatProdAlmEst BOOLEAN, CatProdAlmImg VARCHAR(255), PRIMARY KEY (CatProdAlmCod));
CREATE TABLE cliente (ClieDni INTEGER NOT NULL, ClieApe VARCHAR(255), ClieEst BOOLEAN, ClieMail VARCHAR(255), ClieNom VARCHAR(255), ClieTel INTEGER, TipClieCod INTEGER, PRIMARY KEY (ClieDni));
CREATE TABLE usuario (UsuCod  SERIAL NOT NULL, UsuEst BOOLEAN, UsuNomUsu VARCHAR(255), UsuPasUsu VARCHAR(255), EmpDni INTEGER, TipUsuCod INTEGER, PRIMARY KEY (UsuCod));
CREATE TABLE facturaciond_extra (FacExtDetCod  SERIAL NOT NULL, FacExtCant INTEGER, FacExtPrec FLOAT, ExtCod INTEGER, FacDetSec INTEGER, PRIMARY KEY (FacExtDetCod));
CREATE TABLE categoria_producto_extra (CatProdCod INTEGER NOT NULL, CatExtCod INTEGER NOT NULL, PRIMARY KEY (CatProdCod, CatExtCod));
ALTER TABLE almacen ADD CONSTRAINT FK_almacen_IngCod FOREIGN KEY (IngCod) REFERENCES producto_almacen (ProdAlmCod);
ALTER TABLE cierre_caja ADD CONSTRAINT FK_cierre_caja_AperCajCod FOREIGN KEY (AperCajCod) REFERENCES apertura_caja (AperCajCod);
ALTER TABLE egreso_kardex ADD CONSTRAINT FK_egreso_kardex_KarCod FOREIGN KEY (KarCod) REFERENCES kardex (KarCod);
ALTER TABLE kardex ADD CONSTRAINT FK_kardex_ProdAlmCod FOREIGN KEY (ProdAlmCod) REFERENCES producto_almacen (ProdAlmCod);
ALTER TABLE registro_falta ADD CONSTRAINT FK_registro_falta_EmpDni FOREIGN KEY (EmpDni) REFERENCES empleado (EmpDni);
ALTER TABLE registro_falta ADD CONSTRAINT FK_registro_falta_TipFalCod FOREIGN KEY (TipFalCod) REFERENCES tipo_falta (TipFalCod);
ALTER TABLE apertura_caja ADD CONSTRAINT FK_apertura_caja_UsuCod FOREIGN KEY (UsuCod) REFERENCES usuario (UsuCod);
ALTER TABLE facturacion ADD CONSTRAINT FK_facturacion_ClieDni FOREIGN KEY (ClieDni) REFERENCES cliente (ClieDni);
ALTER TABLE facturacion ADD CONSTRAINT FK_facturacion_TipFacCod FOREIGN KEY (TipFacCod) REFERENCES tipo_facturacion (TipFacCod);
ALTER TABLE facturacion ADD CONSTRAINT FK_facturacion_UsuCod FOREIGN KEY (UsuCod) REFERENCES usuario (UsuCod);
ALTER TABLE producto ADD CONSTRAINT FK_producto_CatProdCod FOREIGN KEY (CatProdCod) REFERENCES categoria_producto (CatProdCod);
ALTER TABLE facturacion_detalle ADD CONSTRAINT FK_facturacion_detalle_ProCod FOREIGN KEY (ProCod) REFERENCES producto (ProCod);
ALTER TABLE facturacion_detalle ADD CONSTRAINT FK_facturacion_detalle_FacCod FOREIGN KEY (FacCod) REFERENCES facturacion (FacCod);
ALTER TABLE promociones ADD CONSTRAINT FK_promociones_ProCod FOREIGN KEY (ProCod) REFERENCES producto (ProCod);
ALTER TABLE extras ADD CONSTRAINT FK_extras_CatExtCod FOREIGN KEY (CatExtCod) REFERENCES categoria_extra (CatExtCod);
ALTER TABLE empleado ADD CONSTRAINT FK_empleado_CarCod FOREIGN KEY (CarCod) REFERENCES cargo (CarCod);
ALTER TABLE empleado ADD CONSTRAINT FK_empleado_TurCod FOREIGN KEY (TurCod) REFERENCES turno (TurCod);
ALTER TABLE gastos ADD CONSTRAINT FK_gastos_EmpDni FOREIGN KEY (EmpDni) REFERENCES empleado (EmpDni);
ALTER TABLE gastos ADD CONSTRAINT FK_gastos_TipGasCod FOREIGN KEY (TipGasCod) REFERENCES tipo_gasto (TipGasCod);
ALTER TABLE gastos ADD CONSTRAINT FK_gastos_TipDocCod FOREIGN KEY (TipDocCod) REFERENCES tipo_documento (TipDocCod);
ALTER TABLE gastos ADD CONSTRAINT FK_gastos_ProvRuc FOREIGN KEY (ProvRuc) REFERENCES proveedor (ProvRuc);
ALTER TABLE ingreso_kardex ADD CONSTRAINT FK_ingreso_kardex_GasCod FOREIGN KEY (GasCod) REFERENCES gastos (GasCod);
ALTER TABLE ingreso_kardex ADD CONSTRAINT FK_ingreso_kardex_KarCod FOREIGN KEY (KarCod) REFERENCES kardex (KarCod);
ALTER TABLE producto_almacen ADD CONSTRAINT FK_producto_almacen_CatProdAlmCod FOREIGN KEY (CatProdAlmCod) REFERENCES categoria_producto_almacen (CatProdAlmCod);
ALTER TABLE producto_almacen ADD CONSTRAINT FK_producto_almacen_UniMedCod FOREIGN KEY (UniMedCod) REFERENCES unidad_medida (UniMedCod);
ALTER TABLE cliente ADD CONSTRAINT FK_cliente_TipClieCod FOREIGN KEY (TipClieCod) REFERENCES tipo_cliente (TipClieCod);
ALTER TABLE usuario ADD CONSTRAINT FK_usuario_EmpDni FOREIGN KEY (EmpDni) REFERENCES empleado (EmpDni);
ALTER TABLE usuario ADD CONSTRAINT FK_usuario_TipUsuCod FOREIGN KEY (TipUsuCod) REFERENCES tipousuario (TipUsuCod);
ALTER TABLE facturaciond_extra ADD CONSTRAINT FK_facturaciond_extra_ExtCod FOREIGN KEY (ExtCod) REFERENCES extras (ExtCod);
ALTER TABLE facturaciond_extra ADD CONSTRAINT FK_facturaciond_extra_FacDetSec FOREIGN KEY (FacDetSec) REFERENCES facturacion_detalle (FacDetSec);
ALTER TABLE categoria_producto_extra ADD CONSTRAINT FK_categoria_producto_extra_CatProdCod FOREIGN KEY (CatProdCod) REFERENCES categoria_producto (CatProdCod);
ALTER TABLE categoria_producto_extra ADD CONSTRAINT FK_categoria_producto_extra_CatExtCod FOREIGN KEY (CatExtCod) REFERENCES categoria_extra (CatExtCod);